version: "3.7"

services:
  app:
    image: flask-rest
    ports:
      - 8001:5001
    environment:
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017

  mongodb:
    image: mongo:4.4.3
    volumes:
      - /home/amondal/workspaces/pyws/mongo-data:/data/db
